@startuml
class edu.byu.cs.tweeter.client.model.service.paged.StoryService {
# PagedTask getPageTask(AuthToken,User,int,Status,GetPagedObserver<Status>)
}


edu.byu.cs.tweeter.client.model.service.paged.PagedService <|-- edu.byu.cs.tweeter.client.model.service.paged.StoryService
@enduml